config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories do
    resources :articles
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  validates :title, :body, :category_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @category = Category.find_by_id(params[:category_id])
  end

  def show
    @category = Category.find_by_id(params[:category_id])
    @article = Article.find_by_id(params[:id])
  end

  def new
    @category = Category.find_by_id(params[:category_id])
    @article = @category.articles.build
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @article = Article.find_by_id(params[:id])
  end

  def create
    @category = Category.find_by_id(params[:category_id])
    @article = @category.articles.new(art_params)

    if @article.save
      redirect_to category_articles_path(@article.category.id)
    else
      render 'new'
    end
  end

  def update
    @category = Category.find_by_id(params[:category_id])
    @article = Article.find_by_id(params[:id])

    if @article.update(art_params)
      redirect_to category_article_path(@category, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])
    @article.destroy

    redirect_to category_articles_path
  end

  private
    def art_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find_by_id(params[:id])
  end

  def create
    @category = Category.new(cat_params)

    if @category.save
      redirect_to category_articles_path(@category.id)
    else
      render 'new'
    end
  end

  def update
    @category = Category.find_by_id(params[:id])

    if @category.update(cat_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find_by_id(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def cat_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_errors.html.erb
<% if @article.errors %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Page</h1>

<%= render 'articles/errors' %>

<%= form_for :article, url: category_article_path(@category, @article), method: :put do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "#{@category.name} Home", category_articles_path(@category) %>

app/views/articles/index.html.erb
<h1><%=@category.name %></h1>

<h3>Articles</h3>
<ul>
  <% @category.articles.each do |art| %>
    <li><%= link_to art.title, category_article_path(@category.id, art.id) %></li>
    <%= link_to 'Edit', edit_category_article_path(art.category, art) %>
    <%= link_to 'Delete', category_article_path(art.category, art), method: :delete %>
  <% end %>
</ul>

<%= link_to 'New Article', new_category_article_path %> <br>
<%= link_to 'Home', categories_path %>

app/views/articles/new.html.erb
<h1>New Article Page</h1>

<%= render 'articles/errors' %>

<%= form_for :article, url: category_articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "#{@category.name} Home", category_articles_path(@category) %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <%= @article.body %>
</p>

<%= link_to "#{@category.name} Home", category_articles_path(@category) %>

app/views/categories/_errors.html.erb
<% if @category.errors %>
  <ul>
    <% @category.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %><br>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Page</h1>

<%= render 'categories/errors' %>

<%= render 'categories/form' %>


<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Craigslist Jr</h1>


<ul>
  <% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_articles_path(cat.id) %></li>
    <%= link_to 'Edit', edit_category_path(cat) %>
    <%= link_to 'Delete', category_path(cat), method: :delete %>
    <br>
    <br>
  <% end %>
</ul>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Create New Category</h1>

<%= render 'categories/errors' %>


<%= render 'categories/form' %>

<%= link_to 'Home', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraiglistJrRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>